Repository kalviumcommunity/S63_KartikBhardwaj_capstone_Bookhive, pull requests merged in 2025-05, with the labels that each got.

#45 Implemented authentication (username / password) in application
  backend/server.js
Labels: Review effort 1/5

#48 Implemented authentication (3rd party - like google) in application
  README.md
Labels: Review effort 1/5

#49 Implementing 'update' and 'delete' an entity in React app
  README.md
  backend/server.js
Labels: Review effort 1/5

#52 Completed LangChain.js
  backend/package-lock.json
  backend/package.json
  backend/routes/aiRoutes.js
  backend/server.js
  backend/services/aiService.js
  backend/services/hybridOtpService.js
  frontend/src/App.jsx
  frontend/src/components/AIAssistantWidget.jsx
  frontend/src/components/BookChat.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/OTPVerification.jsx
  frontend/src/components/ReadingMoodMatcher.jsx
  frontend/src/components/SignUp.jsx
  frontend/src/context/AuthContext.jsx
  frontend/src/styles/AIAssistantWidget.css
  frontend/src/styles/BookChat.css
  frontend/src/styles/OTPVerificationNew.css
Labels: Review effort 4/5

#55 add book recommendation form for user submissions
  .DS_Store
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/RecommendBook.jsx
Labels: Review effort 2/5
